version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "running tests"
      - run: npm install
      - run: npm run test
  hithere:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout 
      - run: echo "Helloooo"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere